(FileStream oldFileNamed: 'preTracer.st') fileIn.
(FileStream oldFileNamed: 'SystemTracer.st') fileIn.
(FileStream oldFileNamed: 'TracerChanges-di.cs') fileIn.
(FileStream oldFileNamed: 'NewTracerChanges-di.st') fileIn.
(FileStream oldFileNamed: 'SimulatorFixes-di.cs') fileIn.

(FileStream oldFileNamed: 'TeleMorphic1.cs') fileIn.
(FileStream oldFileNamed: 'TeleMorphic2.cs') fileIn.
(FileStream oldFileNamed: 'TeleMorphic3.cs') fileIn.

(FileStream oldFileNamed: 'TextMorphMods-di.cs') fileIn.
(FileStream oldFileNamed: 'TextMorphTweaks-di.cs') fileIn.

(FileStream oldFileNamed: 'macSockBugFix.cs') fileIn.
(FileStream oldFileNamed: 'jhmMenuExtras.cs') fileIn.
(FileStream oldFileNamed: 'jhmMiscExtras.cs') fileIn.

(FileStream oldFileNamed: 'Sundry-di.cs') fileIn.

(FileStream oldFileNamed: 'newClassDefs.cs') fileIn.
(FileStream oldFileNamed: 'jhm122FixesOct4.cs') fileIn.

(FileStream oldFileNamed: 'TextFitChanges-di.cs') fileIn.

